---
title: "Sports Analysis"
author: "Noah Hulse"
date: "2023-01-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
data = read_csv("cbb2.csv")
data
```
```{r}
upset = data %>% filter(SEED > 8)  %>% filter(!grepl('R64', POSTSEASON)) %>% filter(!grepl('R68', POSTSEASON))
upset

upset.no = data %>% filter(SEED > 8) %>% filter(SEED < 15) %>% filter(grepl("R64|R68", POSTSEASON))
upset.no
```
```{r}
mean(upset$ADJ_T)
mean(upset.no$ADJ_T)

t.test(upset$ADJ_T, upset.no$ADJ_T)
```
```{r}
upset.far = data %>% filter(SEED > 8) %>% filter (!grepl('R64|R68|R32', POSTSEASON))
upset.far
```


```{r}
mean(upset.far$ADJ_T)

```

```{r}
data.highseeds = data %>% filter(SEED > 8)

data.upset <- data.highseeds %>% 
  mutate(Upset = ifelse(POSTSEASON == "R64" | POSTSEASON == "R68", 0, 1))

data.upset
```
```{r}
lm_model <- lm(Upset ~ ADJ_T, data.upset)
summary(lm_model)
```

```{r}
boxplot(ADJ_T~Upset, data.upset)
```
```{r}


```

